// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { ListNotebooksEndpointApiNotebooksGetData, ListNotebooksEndpointApiNotebooksGetResponses, CreateNotebookApiNotebooksPostData, CreateNotebookApiNotebooksPostResponses, GetNotebookApiNotebooksNotebookIdGetData, GetNotebookApiNotebooksNotebookIdGetResponses, GetNotebookApiNotebooksNotebookIdGetErrors, UpdateDbConnectionApiNotebooksNotebookIdDbPutData, UpdateDbConnectionApiNotebooksNotebookIdDbPutResponses, UpdateDbConnectionApiNotebooksNotebookIdDbPutErrors, RenameNotebookApiNotebooksNotebookIdNamePutData, RenameNotebookApiNotebooksNotebookIdNamePutResponses, RenameNotebookApiNotebooksNotebookIdNamePutErrors, CreateCellApiNotebooksNotebookIdCellsPostData, CreateCellApiNotebooksNotebookIdCellsPostResponses, CreateCellApiNotebooksNotebookIdCellsPostErrors, DeleteCellApiNotebooksNotebookIdCellsCellIdDeleteData, DeleteCellApiNotebooksNotebookIdCellsCellIdDeleteResponses, DeleteCellApiNotebooksNotebookIdCellsCellIdDeleteErrors, UpdateCellApiNotebooksNotebookIdCellsCellIdPutData, UpdateCellApiNotebooksNotebookIdCellsCellIdPutResponses, UpdateCellApiNotebooksNotebookIdCellsCellIdPutErrors, HealthHealthGetData, HealthHealthGetResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List Notebooks Endpoint
 * List all available notebooks
 */
export const listNotebooksEndpointApiNotebooksGet = <ThrowOnError extends boolean = false>(options?: Options<ListNotebooksEndpointApiNotebooksGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListNotebooksEndpointApiNotebooksGetResponses, unknown, ThrowOnError>({
        url: '/api/notebooks',
        ...options
    });
};

/**
 * Create Notebook
 * Create a new notebook with one empty Python cell
 */
export const createNotebookApiNotebooksPost = <ThrowOnError extends boolean = false>(options?: Options<CreateNotebookApiNotebooksPostData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<CreateNotebookApiNotebooksPostResponses, unknown, ThrowOnError>({
        url: '/api/notebooks',
        ...options
    });
};

/**
 * Get Notebook
 * Get notebook details
 */
export const getNotebookApiNotebooksNotebookIdGet = <ThrowOnError extends boolean = false>(options: Options<GetNotebookApiNotebooksNotebookIdGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetNotebookApiNotebooksNotebookIdGetResponses, GetNotebookApiNotebooksNotebookIdGetErrors, ThrowOnError>({
        url: '/api/notebooks/{notebook_id}',
        ...options
    });
};

/**
 * Update Db Connection
 * Update database connection string
 */
export const updateDbConnectionApiNotebooksNotebookIdDbPut = <ThrowOnError extends boolean = false>(options: Options<UpdateDbConnectionApiNotebooksNotebookIdDbPutData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<UpdateDbConnectionApiNotebooksNotebookIdDbPutResponses, UpdateDbConnectionApiNotebooksNotebookIdDbPutErrors, ThrowOnError>({
        url: '/api/notebooks/{notebook_id}/db',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Rename Notebook
 * Update notebook name
 */
export const renameNotebookApiNotebooksNotebookIdNamePut = <ThrowOnError extends boolean = false>(options: Options<RenameNotebookApiNotebooksNotebookIdNamePutData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<RenameNotebookApiNotebooksNotebookIdNamePutResponses, RenameNotebookApiNotebooksNotebookIdNamePutErrors, ThrowOnError>({
        url: '/api/notebooks/{notebook_id}/name',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Create Cell
 * Create a new cell
 */
export const createCellApiNotebooksNotebookIdCellsPost = <ThrowOnError extends boolean = false>(options: Options<CreateCellApiNotebooksNotebookIdCellsPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateCellApiNotebooksNotebookIdCellsPostResponses, CreateCellApiNotebooksNotebookIdCellsPostErrors, ThrowOnError>({
        url: '/api/notebooks/{notebook_id}/cells',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete Cell
 * Delete a cell
 */
export const deleteCellApiNotebooksNotebookIdCellsCellIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteCellApiNotebooksNotebookIdCellsCellIdDeleteData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteCellApiNotebooksNotebookIdCellsCellIdDeleteResponses, DeleteCellApiNotebooksNotebookIdCellsCellIdDeleteErrors, ThrowOnError>({
        url: '/api/notebooks/{notebook_id}/cells/{cell_id}',
        ...options
    });
};

/**
 * Update Cell
 * Update cell code
 */
export const updateCellApiNotebooksNotebookIdCellsCellIdPut = <ThrowOnError extends boolean = false>(options: Options<UpdateCellApiNotebooksNotebookIdCellsCellIdPutData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<UpdateCellApiNotebooksNotebookIdCellsCellIdPutResponses, UpdateCellApiNotebooksNotebookIdCellsCellIdPutErrors, ThrowOnError>({
        url: '/api/notebooks/{notebook_id}/cells/{cell_id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Health
 */
export const healthHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthHealthGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<HealthHealthGetResponses, unknown, ThrowOnError>({
        url: '/health',
        ...options
    });
};