// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { ListNotebooksEndpointApiV1NotebooksGetData, ListNotebooksEndpointApiV1NotebooksGetResponses, CreateNotebookApiV1NotebooksPostData, CreateNotebookApiV1NotebooksPostResponses, DeleteNotebookEndpointApiV1NotebooksNotebookIdDeleteData, DeleteNotebookEndpointApiV1NotebooksNotebookIdDeleteResponses, DeleteNotebookEndpointApiV1NotebooksNotebookIdDeleteErrors, GetNotebookApiV1NotebooksNotebookIdGetData, GetNotebookApiV1NotebooksNotebookIdGetResponses, GetNotebookApiV1NotebooksNotebookIdGetErrors, RenameNotebookApiV1NotebooksNotebookIdNamePutData, RenameNotebookApiV1NotebooksNotebookIdNamePutResponses, RenameNotebookApiV1NotebooksNotebookIdNamePutErrors, UpdateDbConnectionApiV1NotebooksNotebookIdDbPutData, UpdateDbConnectionApiV1NotebooksNotebookIdDbPutResponses, UpdateDbConnectionApiV1NotebooksNotebookIdDbPutErrors, CreateCellApiV1NotebooksNotebookIdCellsPostData, CreateCellApiV1NotebooksNotebookIdCellsPostResponses, CreateCellApiV1NotebooksNotebookIdCellsPostErrors, DeleteCellApiV1NotebooksNotebookIdCellsCellIdDeleteData, DeleteCellApiV1NotebooksNotebookIdCellsCellIdDeleteResponses, DeleteCellApiV1NotebooksNotebookIdCellsCellIdDeleteErrors, UpdateCellApiV1NotebooksNotebookIdCellsCellIdPutData, UpdateCellApiV1NotebooksNotebookIdCellsCellIdPutResponses, UpdateCellApiV1NotebooksNotebookIdCellsCellIdPutErrors, HealthCheckHealthGetData, HealthCheckHealthGetResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List Notebooks Endpoint
 * List all notebooks.
 */
export const listNotebooksEndpointApiV1NotebooksGet = <ThrowOnError extends boolean = false>(options?: Options<ListNotebooksEndpointApiV1NotebooksGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListNotebooksEndpointApiV1NotebooksGetResponses, unknown, ThrowOnError>({
        url: '/api/v1/notebooks/',
        ...options
    });
};

/**
 * Create Notebook
 * Create a new notebook.
 */
export const createNotebookApiV1NotebooksPost = <ThrowOnError extends boolean = false>(options?: Options<CreateNotebookApiV1NotebooksPostData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<CreateNotebookApiV1NotebooksPostResponses, unknown, ThrowOnError>({
        url: '/api/v1/notebooks/',
        ...options
    });
};

/**
 * Delete Notebook Endpoint
 * Delete a notebook.
 */
export const deleteNotebookEndpointApiV1NotebooksNotebookIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteNotebookEndpointApiV1NotebooksNotebookIdDeleteData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteNotebookEndpointApiV1NotebooksNotebookIdDeleteResponses, DeleteNotebookEndpointApiV1NotebooksNotebookIdDeleteErrors, ThrowOnError>({
        url: '/api/v1/notebooks/{notebook_id}',
        ...options
    });
};

/**
 * Get Notebook
 * Get a specific notebook.
 */
export const getNotebookApiV1NotebooksNotebookIdGet = <ThrowOnError extends boolean = false>(options: Options<GetNotebookApiV1NotebooksNotebookIdGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetNotebookApiV1NotebooksNotebookIdGetResponses, GetNotebookApiV1NotebooksNotebookIdGetErrors, ThrowOnError>({
        url: '/api/v1/notebooks/{notebook_id}',
        ...options
    });
};

/**
 * Rename Notebook
 * Rename a notebook.
 */
export const renameNotebookApiV1NotebooksNotebookIdNamePut = <ThrowOnError extends boolean = false>(options: Options<RenameNotebookApiV1NotebooksNotebookIdNamePutData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<RenameNotebookApiV1NotebooksNotebookIdNamePutResponses, RenameNotebookApiV1NotebooksNotebookIdNamePutErrors, ThrowOnError>({
        url: '/api/v1/notebooks/{notebook_id}/name',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Update Db Connection
 * Update database connection string.
 */
export const updateDbConnectionApiV1NotebooksNotebookIdDbPut = <ThrowOnError extends boolean = false>(options: Options<UpdateDbConnectionApiV1NotebooksNotebookIdDbPutData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<UpdateDbConnectionApiV1NotebooksNotebookIdDbPutResponses, UpdateDbConnectionApiV1NotebooksNotebookIdDbPutErrors, ThrowOnError>({
        url: '/api/v1/notebooks/{notebook_id}/db',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Create Cell
 * Create a new cell in a notebook.
 */
export const createCellApiV1NotebooksNotebookIdCellsPost = <ThrowOnError extends boolean = false>(options: Options<CreateCellApiV1NotebooksNotebookIdCellsPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateCellApiV1NotebooksNotebookIdCellsPostResponses, CreateCellApiV1NotebooksNotebookIdCellsPostErrors, ThrowOnError>({
        url: '/api/v1/notebooks/{notebook_id}/cells/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete Cell
 * Delete a cell.
 */
export const deleteCellApiV1NotebooksNotebookIdCellsCellIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteCellApiV1NotebooksNotebookIdCellsCellIdDeleteData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteCellApiV1NotebooksNotebookIdCellsCellIdDeleteResponses, DeleteCellApiV1NotebooksNotebookIdCellsCellIdDeleteErrors, ThrowOnError>({
        url: '/api/v1/notebooks/{notebook_id}/cells/{cell_id}',
        ...options
    });
};

/**
 * Update Cell
 * Update a cell's code.
 */
export const updateCellApiV1NotebooksNotebookIdCellsCellIdPut = <ThrowOnError extends boolean = false>(options: Options<UpdateCellApiV1NotebooksNotebookIdCellsCellIdPutData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<UpdateCellApiV1NotebooksNotebookIdCellsCellIdPutResponses, UpdateCellApiV1NotebooksNotebookIdCellsCellIdPutErrors, ThrowOnError>({
        url: '/api/v1/notebooks/{notebook_id}/cells/{cell_id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Health Check
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckHealthGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<HealthCheckHealthGetResponses, unknown, ThrowOnError>({
        url: '/health',
        ...options
    });
};