// This file is auto-generated by @hey-api/openapi-ts

/**
 * CellResponse
 */
export type CellResponse = {
    /**
     * Id
     */
    id: string;
    type: CellType;
    /**
     * Code
     */
    code: string;
    status: CellStatus;
    /**
     * Stdout
     */
    stdout?: string | null;
    /**
     * Outputs
     */
    outputs: Array<OutputResponse>;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Reads
     */
    reads: Array<string>;
    /**
     * Writes
     */
    writes: Array<string>;
};

/**
 * CellStatus
 */
export type CellStatus = 'idle' | 'running' | 'success' | 'error' | 'blocked';

/**
 * CellType
 */
export type CellType = 'python' | 'sql';

/**
 * CreateCellRequest
 */
export type CreateCellRequest = {
    type: CellType;
};

/**
 * CreateCellResponse
 */
export type CreateCellResponse = {
    /**
     * Cell Id
     */
    cell_id: string;
};

/**
 * CreateNotebookResponse
 */
export type CreateNotebookResponse = {
    /**
     * Notebook Id
     */
    notebook_id: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ListNotebooksResponse
 */
export type ListNotebooksResponse = {
    /**
     * Notebooks
     */
    notebooks: Array<NotebookMetadataResponse>;
};

/**
 * NotebookMetadataResponse
 */
export type NotebookMetadataResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
};

/**
 * NotebookResponse
 */
export type NotebookResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Db Conn String
     */
    db_conn_string?: string | null;
    /**
     * Cells
     */
    cells: Array<CellResponse>;
};

/**
 * OutputResponse
 */
export type OutputResponse = {
    /**
     * Mime Type
     */
    mime_type: string;
    /**
     * Data
     */
    data: string | TableData | {
        [key: string]: unknown;
    } | Array<unknown>;
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: string | number | number;
    } | null;
};

/**
 * RenameNotebookRequest
 */
export type RenameNotebookRequest = {
    /**
     * Name
     */
    name: string;
};

/**
 * TableData
 * Table data structure for pandas DataFrames and SQL results
 */
export type TableData = {
    /**
     * Type
     */
    type: 'table';
    /**
     * Columns
     */
    columns: Array<string>;
    /**
     * Rows
     */
    rows: Array<Array<string | number | number | boolean | null>>;
    /**
     * Truncated
     */
    truncated?: string | null;
};

/**
 * UpdateCellRequest
 */
export type UpdateCellRequest = {
    /**
     * Code
     */
    code: string;
};

/**
 * UpdateDbConnectionRequest
 */
export type UpdateDbConnectionRequest = {
    /**
     * Connection String
     */
    connection_string: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ListNotebooksEndpointApiNotebooksGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/notebooks';
};

export type ListNotebooksEndpointApiNotebooksGetResponses = {
    /**
     * Successful Response
     */
    200: ListNotebooksResponse;
};

export type ListNotebooksEndpointApiNotebooksGetResponse = ListNotebooksEndpointApiNotebooksGetResponses[keyof ListNotebooksEndpointApiNotebooksGetResponses];

export type CreateNotebookApiNotebooksPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/notebooks';
};

export type CreateNotebookApiNotebooksPostResponses = {
    /**
     * Successful Response
     */
    200: CreateNotebookResponse;
};

export type CreateNotebookApiNotebooksPostResponse = CreateNotebookApiNotebooksPostResponses[keyof CreateNotebookApiNotebooksPostResponses];

export type GetNotebookApiNotebooksNotebookIdGetData = {
    body?: never;
    path: {
        /**
         * Notebook Id
         */
        notebook_id: string;
    };
    query?: never;
    url: '/api/notebooks/{notebook_id}';
};

export type GetNotebookApiNotebooksNotebookIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetNotebookApiNotebooksNotebookIdGetError = GetNotebookApiNotebooksNotebookIdGetErrors[keyof GetNotebookApiNotebooksNotebookIdGetErrors];

export type GetNotebookApiNotebooksNotebookIdGetResponses = {
    /**
     * Successful Response
     */
    200: NotebookResponse;
};

export type GetNotebookApiNotebooksNotebookIdGetResponse = GetNotebookApiNotebooksNotebookIdGetResponses[keyof GetNotebookApiNotebooksNotebookIdGetResponses];

export type UpdateDbConnectionApiNotebooksNotebookIdDbPutData = {
    body: UpdateDbConnectionRequest;
    path: {
        /**
         * Notebook Id
         */
        notebook_id: string;
    };
    query?: never;
    url: '/api/notebooks/{notebook_id}/db';
};

export type UpdateDbConnectionApiNotebooksNotebookIdDbPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateDbConnectionApiNotebooksNotebookIdDbPutError = UpdateDbConnectionApiNotebooksNotebookIdDbPutErrors[keyof UpdateDbConnectionApiNotebooksNotebookIdDbPutErrors];

export type UpdateDbConnectionApiNotebooksNotebookIdDbPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RenameNotebookApiNotebooksNotebookIdNamePutData = {
    body: RenameNotebookRequest;
    path: {
        /**
         * Notebook Id
         */
        notebook_id: string;
    };
    query?: never;
    url: '/api/notebooks/{notebook_id}/name';
};

export type RenameNotebookApiNotebooksNotebookIdNamePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RenameNotebookApiNotebooksNotebookIdNamePutError = RenameNotebookApiNotebooksNotebookIdNamePutErrors[keyof RenameNotebookApiNotebooksNotebookIdNamePutErrors];

export type RenameNotebookApiNotebooksNotebookIdNamePutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateCellApiNotebooksNotebookIdCellsPostData = {
    body: CreateCellRequest;
    path: {
        /**
         * Notebook Id
         */
        notebook_id: string;
    };
    query?: never;
    url: '/api/notebooks/{notebook_id}/cells';
};

export type CreateCellApiNotebooksNotebookIdCellsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCellApiNotebooksNotebookIdCellsPostError = CreateCellApiNotebooksNotebookIdCellsPostErrors[keyof CreateCellApiNotebooksNotebookIdCellsPostErrors];

export type CreateCellApiNotebooksNotebookIdCellsPostResponses = {
    /**
     * Successful Response
     */
    200: CreateCellResponse;
};

export type CreateCellApiNotebooksNotebookIdCellsPostResponse = CreateCellApiNotebooksNotebookIdCellsPostResponses[keyof CreateCellApiNotebooksNotebookIdCellsPostResponses];

export type DeleteCellApiNotebooksNotebookIdCellsCellIdDeleteData = {
    body?: never;
    path: {
        /**
         * Notebook Id
         */
        notebook_id: string;
        /**
         * Cell Id
         */
        cell_id: string;
    };
    query?: never;
    url: '/api/notebooks/{notebook_id}/cells/{cell_id}';
};

export type DeleteCellApiNotebooksNotebookIdCellsCellIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCellApiNotebooksNotebookIdCellsCellIdDeleteError = DeleteCellApiNotebooksNotebookIdCellsCellIdDeleteErrors[keyof DeleteCellApiNotebooksNotebookIdCellsCellIdDeleteErrors];

export type DeleteCellApiNotebooksNotebookIdCellsCellIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateCellApiNotebooksNotebookIdCellsCellIdPutData = {
    body: UpdateCellRequest;
    path: {
        /**
         * Notebook Id
         */
        notebook_id: string;
        /**
         * Cell Id
         */
        cell_id: string;
    };
    query?: never;
    url: '/api/notebooks/{notebook_id}/cells/{cell_id}';
};

export type UpdateCellApiNotebooksNotebookIdCellsCellIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCellApiNotebooksNotebookIdCellsCellIdPutError = UpdateCellApiNotebooksNotebookIdCellsCellIdPutErrors[keyof UpdateCellApiNotebooksNotebookIdCellsCellIdPutErrors];

export type UpdateCellApiNotebooksNotebookIdCellsCellIdPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};