// This file is auto-generated by @hey-api/openapi-ts

/**
 * CellResponse
 */
export type CellResponse = {
    /**
     * Id
     */
    id: string;
    type: CellType;
    /**
     * Code
     */
    code: string;
    status: CellStatus;
    /**
     * Stdout
     */
    stdout?: string | null;
    /**
     * Outputs
     */
    outputs: Array<OutputResponse>;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Reads
     */
    reads: Array<string>;
    /**
     * Writes
     */
    writes: Array<string>;
};

/**
 * CellStatus
 */
export type CellStatus = 'idle' | 'running' | 'success' | 'error' | 'blocked';

/**
 * CellType
 */
export type CellType = 'python' | 'sql';

/**
 * ChatMessage
 */
export type ChatMessage = {
    /**
     * Role
     */
    role: string;
    /**
     * Content
     */
    content: string;
};

/**
 * ChatRequest
 */
export type ChatRequest = {
    /**
     * Messages
     */
    messages: Array<ChatMessage>;
};

/**
 * CreateCellRequest
 */
export type CreateCellRequest = {
    type: CellType;
    /**
     * After Cell Id
     */
    after_cell_id?: string | null;
};

/**
 * CreateCellResponse
 */
export type CreateCellResponse = {
    /**
     * Cell Id
     */
    cell_id: string;
};

/**
 * CreateNotebookResponse
 */
export type CreateNotebookResponse = {
    /**
     * Notebook Id
     */
    notebook_id: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ListNotebooksResponse
 */
export type ListNotebooksResponse = {
    /**
     * Notebooks
     */
    notebooks: Array<NotebookMetadataResponse>;
};

/**
 * NotebookMetadataResponse
 */
export type NotebookMetadataResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
};

/**
 * NotebookResponse
 */
export type NotebookResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Db Conn String
     */
    db_conn_string?: string | null;
    /**
     * Cells
     */
    cells: Array<CellResponse>;
};

/**
 * OutputResponse
 */
export type OutputResponse = {
    /**
     * Mime Type
     */
    mime_type: string;
    /**
     * Data
     */
    data: string | TableData | {
        [key: string]: unknown;
    } | Array<unknown>;
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: string | number | number;
    } | null;
};

/**
 * RenameNotebookRequest
 */
export type RenameNotebookRequest = {
    /**
     * Name
     */
    name: string;
};

/**
 * TableData
 * Table data structure for pandas DataFrames and SQL results
 */
export type TableData = {
    /**
     * Type
     */
    type: 'table';
    /**
     * Columns
     */
    columns: Array<string>;
    /**
     * Rows
     */
    rows: Array<Array<string | number | number | boolean | null>>;
    /**
     * Truncated
     */
    truncated?: string | null;
};

/**
 * UpdateCellRequest
 */
export type UpdateCellRequest = {
    /**
     * Code
     */
    code: string;
};

/**
 * UpdateDbConnectionRequest
 */
export type UpdateDbConnectionRequest = {
    /**
     * Connection String
     */
    connection_string: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ListNotebooksEndpointApiV1NotebooksGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/notebooks/';
};

export type ListNotebooksEndpointApiV1NotebooksGetResponses = {
    /**
     * Successful Response
     */
    200: ListNotebooksResponse;
};

export type ListNotebooksEndpointApiV1NotebooksGetResponse = ListNotebooksEndpointApiV1NotebooksGetResponses[keyof ListNotebooksEndpointApiV1NotebooksGetResponses];

export type CreateNotebookApiV1NotebooksPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/notebooks/';
};

export type CreateNotebookApiV1NotebooksPostResponses = {
    /**
     * Successful Response
     */
    200: CreateNotebookResponse;
};

export type CreateNotebookApiV1NotebooksPostResponse = CreateNotebookApiV1NotebooksPostResponses[keyof CreateNotebookApiV1NotebooksPostResponses];

export type DeleteNotebookEndpointApiV1NotebooksNotebookIdDeleteData = {
    body?: never;
    path: {
        /**
         * Notebook Id
         */
        notebook_id: string;
    };
    query?: never;
    url: '/api/v1/notebooks/{notebook_id}';
};

export type DeleteNotebookEndpointApiV1NotebooksNotebookIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteNotebookEndpointApiV1NotebooksNotebookIdDeleteError = DeleteNotebookEndpointApiV1NotebooksNotebookIdDeleteErrors[keyof DeleteNotebookEndpointApiV1NotebooksNotebookIdDeleteErrors];

export type DeleteNotebookEndpointApiV1NotebooksNotebookIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetNotebookApiV1NotebooksNotebookIdGetData = {
    body?: never;
    path: {
        /**
         * Notebook Id
         */
        notebook_id: string;
    };
    query?: never;
    url: '/api/v1/notebooks/{notebook_id}';
};

export type GetNotebookApiV1NotebooksNotebookIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetNotebookApiV1NotebooksNotebookIdGetError = GetNotebookApiV1NotebooksNotebookIdGetErrors[keyof GetNotebookApiV1NotebooksNotebookIdGetErrors];

export type GetNotebookApiV1NotebooksNotebookIdGetResponses = {
    /**
     * Successful Response
     */
    200: NotebookResponse;
};

export type GetNotebookApiV1NotebooksNotebookIdGetResponse = GetNotebookApiV1NotebooksNotebookIdGetResponses[keyof GetNotebookApiV1NotebooksNotebookIdGetResponses];

export type UpdateDbConnectionApiV1NotebooksNotebookIdDbPutData = {
    body: UpdateDbConnectionRequest;
    path: {
        /**
         * Notebook Id
         */
        notebook_id: string;
    };
    query?: never;
    url: '/api/v1/notebooks/{notebook_id}/db';
};

export type UpdateDbConnectionApiV1NotebooksNotebookIdDbPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateDbConnectionApiV1NotebooksNotebookIdDbPutError = UpdateDbConnectionApiV1NotebooksNotebookIdDbPutErrors[keyof UpdateDbConnectionApiV1NotebooksNotebookIdDbPutErrors];

export type UpdateDbConnectionApiV1NotebooksNotebookIdDbPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RenameNotebookApiV1NotebooksNotebookIdNamePutData = {
    body: RenameNotebookRequest;
    path: {
        /**
         * Notebook Id
         */
        notebook_id: string;
    };
    query?: never;
    url: '/api/v1/notebooks/{notebook_id}/name';
};

export type RenameNotebookApiV1NotebooksNotebookIdNamePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RenameNotebookApiV1NotebooksNotebookIdNamePutError = RenameNotebookApiV1NotebooksNotebookIdNamePutErrors[keyof RenameNotebookApiV1NotebooksNotebookIdNamePutErrors];

export type RenameNotebookApiV1NotebooksNotebookIdNamePutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateCellApiV1NotebooksNotebookIdCellsPostData = {
    body: CreateCellRequest;
    path: {
        /**
         * Notebook Id
         */
        notebook_id: string;
    };
    query?: never;
    url: '/api/v1/notebooks/{notebook_id}/cells';
};

export type CreateCellApiV1NotebooksNotebookIdCellsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCellApiV1NotebooksNotebookIdCellsPostError = CreateCellApiV1NotebooksNotebookIdCellsPostErrors[keyof CreateCellApiV1NotebooksNotebookIdCellsPostErrors];

export type CreateCellApiV1NotebooksNotebookIdCellsPostResponses = {
    /**
     * Successful Response
     */
    200: CreateCellResponse;
};

export type CreateCellApiV1NotebooksNotebookIdCellsPostResponse = CreateCellApiV1NotebooksNotebookIdCellsPostResponses[keyof CreateCellApiV1NotebooksNotebookIdCellsPostResponses];

export type DeleteCellApiV1NotebooksNotebookIdCellsCellIdDeleteData = {
    body?: never;
    path: {
        /**
         * Notebook Id
         */
        notebook_id: string;
        /**
         * Cell Id
         */
        cell_id: string;
    };
    query?: never;
    url: '/api/v1/notebooks/{notebook_id}/cells/{cell_id}';
};

export type DeleteCellApiV1NotebooksNotebookIdCellsCellIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCellApiV1NotebooksNotebookIdCellsCellIdDeleteError = DeleteCellApiV1NotebooksNotebookIdCellsCellIdDeleteErrors[keyof DeleteCellApiV1NotebooksNotebookIdCellsCellIdDeleteErrors];

export type DeleteCellApiV1NotebooksNotebookIdCellsCellIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateCellApiV1NotebooksNotebookIdCellsCellIdPutData = {
    body: UpdateCellRequest;
    path: {
        /**
         * Notebook Id
         */
        notebook_id: string;
        /**
         * Cell Id
         */
        cell_id: string;
    };
    query?: never;
    url: '/api/v1/notebooks/{notebook_id}/cells/{cell_id}';
};

export type UpdateCellApiV1NotebooksNotebookIdCellsCellIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCellApiV1NotebooksNotebookIdCellsCellIdPutError = UpdateCellApiV1NotebooksNotebookIdCellsCellIdPutErrors[keyof UpdateCellApiV1NotebooksNotebookIdCellsCellIdPutErrors];

export type UpdateCellApiV1NotebooksNotebookIdCellsCellIdPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ChatWithNotebookApiV1ChatChatNotebookIdPostData = {
    body: ChatRequest;
    path: {
        /**
         * Notebook Id
         */
        notebook_id: string;
    };
    query?: never;
    url: '/api/v1/chat/chat/{notebook_id}';
};

export type ChatWithNotebookApiV1ChatChatNotebookIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatWithNotebookApiV1ChatChatNotebookIdPostError = ChatWithNotebookApiV1ChatChatNotebookIdPostErrors[keyof ChatWithNotebookApiV1ChatChatNotebookIdPostErrors];

export type ChatWithNotebookApiV1ChatChatNotebookIdPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};